ORMBenchmarking.Client/Controllers/BenchmarkController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using ORMBenchmarking.AdoNet.Abstract;
using ORMBenchmarking.Client.Models;
using ORMBenchmarking.Dapper.Abstract;
using ORMBenchmarking.EntityFramework.Abstract;
using ORMBenchmarking.Models.Helpers;
using ORMBenchmarking.Models.ViewModel;
using ORMBenchmarking.NHibernate.Abstract;
using static ORMBenchmarking.Models.Helpers.Enums;

namespace ORMBenchmarking.Client.Controllers
{
    public class BenchmarkController : Controller
    {
        private int _queryQuantity = 10;
        private IEntityRepository _entityRepo;
        private INHibernateRepository _nHibernateRepo;
        private IDapperRepository _dapperRepo;
        private IAdoNetRepository _adoNetRepo;

        public BenchmarkController(IEntityRepository entityRepo, INHibernateRepository nHibernateRepo, IDapperRepository dapperRepo, IAdoNetRepository adoNetRepo)
        {
            _entityRepo = entityRepo;
            _nHibernateRepo = nHibernateRepo;
            _dapperRepo = dapperRepo;
            _adoNetRepo = adoNetRepo;
        }

        public IActionResult Index()
        {
           return View();
        }

        public IActionResult Info()
        {
            ViewData["Message"] = "Informacje o aplikacji.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult ExecuteSelectedQuery()
        {
            if (Enum.TryParse(Request.Form["queryType"], out QueryType castedQueryType))
            {
                var executionTimeResults = new Dictionary<LibraryType, List<double>>();

                executionTimeResults.Add(LibraryType.EntityFramework, GetExecutionTimeForEntity(castedQueryType));
                executionTimeResults.Add(LibraryType.NHibernate, GetExecutionTimeForNHibernate(castedQueryType));
                executionTimeResults.Add(LibraryType.Dapper, GetExecutionTimeForDapper(castedQueryType));
                executionTimeResults.Add(LibraryType.Adonet, GetExecutionTimeForAdonet(castedQueryType));

                ExecutionTimeViewModel executionTimeVM = new ExecutionTimeViewModel(executionTimeResults, castedQueryType);

                return View("QueryTimeResult", executionTimeVM);
            }
            return View("Index");
        }

        private List<double> GetExecutionTimeForEntity(QueryType qType)
        {
            List<double> results = new List<double>();
            Stopwatch st = new Stopwatch();
            for (int i = 0; i < _queryQuantity; i++)
            {
                st.Reset();
                st.Start();
                GetQueryToExecute(LibraryType.EntityFramework, qType);
                st.Stop();
                results.Add(st.Elapsed.TotalSeconds);
                GC.Collect();

            }
            return results;
        }

        private List<double> GetExecutionTimeForNHibernate(QueryType qType)
        {
            List<double> results = new List<double>();
            Stopwatch st = new Stopwatch();
            for (int i = 0; i < _queryQuantity; i++)
            {
                st.Reset();
                st.Start();
                GetQueryToExecute(LibraryType.NHibernate, qType);
                st.Stop();
                results.Add(st.Elapsed.TotalSeconds);
                GC.Collect();

            }
            return results;
        }

        private List<double> GetExecutionTimeForDapper(QueryType qType)
        {
            List<double> results = new List<double>();
            Stopwatch st = new Stopwatch();
            for (int i = 0; i < _queryQuantity; i++)
            {
                st.Reset();
                st.Start();
                GetQueryToExecute(LibraryType.Dapper, qType);
                st.Stop();
                results.Add(st.Elapsed.TotalSeconds);
                GC.Collect();

            }
            return results;
        }

        private List<double> GetExecutionTimeForAdonet(QueryType qType)
        {
            List<double> results = new List<double>();
            Stopwatch st = new Stopwatch();
            for (int i = 0; i < _queryQuantity; i++)
            {
                st.Reset();
                st.Start();
                GetQueryToExecute(LibraryType.Adonet, qType);
                st.Stop();
                results.Add(st.Elapsed.TotalSeconds);
            }

            return results;
        }

        private dynamic GetQueryToExecute(LibraryType lType, QueryType qType)
        {
            switch (lType)
            {
                case LibraryType.EntityFramework:
                    switch (qType)
                    {
                        case QueryType.Query_1:
                            return _entityRepo.GetAllTransactions();
                        case QueryType.Query_2:
                            return _entityRepo.GetAllArchiveTransactions();
                        case QueryType.Query_3:
                            return _entityRepo.GetSumOfAllTransactions();
                        case QueryType.Query_4:
                            return _entityRepo.GetEmployeesOlderThan50();
                        case QueryType.Query_5:
                            return _entityRepo.GetSalesByYears();
                        case QueryType.Query_6:
                            return _entityRepo.GetEmployeeQuantityPerDepartment();
                        case QueryType.Query_7:
                            return _entityRepo.GetSalesOrderDetailsWithProductInfo();
                        case QueryType.Query_8:
                            return _entityRepo.GetGroupedOrdersWithStatistics();
                        case QueryType.Query_9:
                            _entityRepo.GetTransactionProductsWithInformation();
                            return null;
                        default:
                            break;
                    }
                    break;
                case LibraryType.NHibernate:
                    switch (qType)
                    {
                        case QueryType.Query_1:
                            return _nHibernateRepo.GetAllTransactions();
                        case QueryType.Query_2:
                            return _nHibernateRepo.GetAllArchiveTransactions();
                        case QueryType.Query_3:
                            return _nHibernateRepo.GetSumOfAllTransactions();
                        case QueryType.Query_4:
                            return _nHibernateRepo.GetEmployeesOlderThan50();
                        case QueryType.Query_5:
                            return _nHibernateRepo.GetSalesByYears();
                        case QueryType.Query_6:
                            return _nHibernateRepo.GetEmployeeQuantityPerDepartment();
                        case QueryType.Query_7:
                            return _nHibernateRepo.GetSalesOrderDetailsWithProductInfo();
                        case QueryType.Query_8:
                            return _nHibernateRepo.GetGroupedOrdersWithStatistics();
                        case QueryType.Query_9:
                            _nHibernateRepo.GetTransactionProductsWithInformation();
                            return null;
                        default:
                            break;
                    }
                    break;
                case LibraryType.Dapper:
                    switch (qType)
                    {
                        case QueryType.Query_1:
                            return _dapperRepo.GetAllTransactions();
                        case QueryType.Query_2:
                            return _dapperRepo.GetAllArchiveTransactions();
                        case QueryType.Query_3:
                            return _dapperRepo.GetSumOfAllTransactions();
                        case QueryType.Query_4:
                            return _dapperRepo.GetEmployeesOlderThan50();
                        case QueryType.Query_5:
                            return _dapperRepo.GetSalesByYears();
                        case QueryType.Query_6:
                            return _dapperRepo.GetEmployeeQuantityPerDepartment();
                        case QueryType.Query_7:
                            return _dapperRepo.GetSalesOrderDetailsWithProductInfo();
                        case QueryType.Query_8:
                            return _dapperRepo.GetGroupedOrdersWithStatistics();
                        case QueryType.Query_9:
                             _dapperRepo.GetTransactionProductsWithInformation();
                             return null;
                        default:
                            break;
                    }
                    break;
                case LibraryType.Adonet:
                    switch (qType)
                    {
                        case QueryType.Query_1:
                            return _adoNetRepo.GetAllTransactions();
                        case QueryType.Query_2:
                            return _adoNetRepo.GetAllArchiveTransactions();
                        case QueryType.Query_3:
                            return _adoNetRepo.GetSumOfAllTransactions();
                        case QueryType.Query_4:
                            return _adoNetRepo.GetEmployeesOlderThan50();
                        case QueryType.Query_5:
                            return _adoNetRepo.GetSalesByYears();
                        case QueryType.Query_6:
                            return _adoNetRepo.GetEmployeeQuantityPerDepartment();
                        case QueryType.Query_7:
                            return _adoNetRepo.GetSalesOrderDetailsWithProductInfo();
                        case QueryType.Query_8:

ORMBenchmarking.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Analiza wydajności dostępu do danych</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container nav-height100">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Benchmark" asp-action="Index" class="navbar-brand"><img src="~/images/logo.png" width="230" class="h-100" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Benchmark" asp-action="Index">Sprawdź wydajność</a></li>
                    <li><a asp-area="" asp-controller="Benchmark" asp-action="Info">Informacje o aplikacji</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content navbar-overlap-fix">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 MGR - Analiza wydajności dostępu do danych</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>